language: objective-c

before_install:
    - brew update
    - brew uninstall xctool && brew install xctool
    - gem install cocoapods

script:
  - xctool -workspace DribbbleTest.xcworkspace -scheme DribbbleTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace DribbbleTest.xcworkspace -scheme DribbbleTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO